name: CI - Test, Build & SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_scan:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORG: sprazitech
      SONAR_PROJECT_KEY: Sprazitech_Practical_Devops_Web_App_Dockerization

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # ================== FRONTEND ==================
      - name: Install Frontend Dependencies
        working-directory: application-code/web-tier
        run: npm install --no-audit --no-fund

      - name: Run Frontend Tests
        working-directory: application-code/web-tier
        run: npm test --if-present

      # ================== BACKEND ==================
      - name: Install Backend Dependencies
        working-directory: application-code/app-tier
        run: npm install --no-audit --no-fund

      - name: Run Backend Tests
        working-directory: application-code/app-tier
        run: npm test --if-present

      # ================== SONAR SCAN ==================
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=application-code
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
            -Dsonar.sourceEncoding=UTF-8

      # ================== QUALITY GATE ==================
      - name: Check SonarCloud Quality Gate
        uses: SonarSource/sonarcloud-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: ${{ env.SONAR_PROJECT_KEY }}
          organization: ${{ env.SONAR_ORG }}
          host-url: https://sonarcloud.io
