name: CI - Test, Build & SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_scan:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Make sure this is added in GitHub Secrets
      SONAR_ORG: sprazitech
      SONAR_PROJECT_KEY: Sprazitech_Practical_Devops_Web_App_Dockerization

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # ========= FRONTEND =========
      - name: Install Frontend Dependencies
        run: |
          cd application-code/web-tier
          npm install

      - name: Run Frontend Tests
        run: |
          cd application-code/web-tier
          npm test --if-present

      # ========= BACKEND =========
      - name: Install Backend Dependencies
        run: |
          cd application-code/app-tier
          npm install

      - name: Run Backend Tests
        run: |
          cd application-code/app-tier
          npm test --if-present

      # ========= SONAR SCAN =========
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required by SonarCloud
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=application-code
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
            -Dsonar.sourceEncoding=UTF-8

      # ========= QUALITY GATE =========
      - name: SonarCloud Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          host-url: https://sonarcloud.io
